/**
 * Generated by orval 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 0.1.0
 */
export interface User {
  /** @minimum 0 */
  id: number;
  name: string;
}

export type getUserResponse200 = {
  data: User
  status: 200
}

export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = (id: number,) => {




  return `http://localhost:8000/api/users/${id}`
}

export const getUser = async (id: number, options?: RequestInit): Promise<getUserResponse> => {

  const res = await fetch(getGetUserUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}
